# Generated by Django 4.2.5 on 2023-10-07 06:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_friends"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="top_friends",
            field=models.ManyToManyField(
                blank=True, related_name="friends_set", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="friends",
            field=models.ManyToManyField(
                blank=True, related_name="top_friends_set", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
