# Generated by Django 4.2.5 on 2023-09-29 15:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="about_post",
            field=models.CharField(
                default="The author did not set an introduction to the topic",
                max_length=1000,
            ),
        ),
    ]
