# Generated by Django 4.2.5 on 2023-10-03 05:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=40, unique=True),
        ),
    ]
