# Generated by Django 4.2.5 on 2023-09-29 04:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="post",
            name="slug",
        ),
    ]
