# Generated by Django 4.2.5 on 2023-09-26 16:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="room",
            name="owner_name",
            field=models.CharField(max_length=128),
        ),
    ]
