# Generated by Django 4.2.5 on 2023-10-24 01:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_groups_groupmessage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="groups",
            old_name="about_groups",
            new_name="about_group",
        ),
    ]
