# Generated by Django 4.2.5 on 2023-09-29 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_remove_post_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="belong_room",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="chat.room"
            ),
        ),
    ]
