# Generated by Django 4.2.5 on 2023-10-01 05:05

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0003_alter_post_about_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="roommessage",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to=chat.models.get_room_image_upload_path
            ),
        ),
    ]
