# Generated by Django 4.2.5 on 2023-09-29 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_alter_post_belong_room"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="title",
            field=models.CharField(max_length=128),
        ),
    ]
