# Generated by Django 4.2.5 on 2023-09-25 08:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_alter_profile_about_me"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="location",
            field=models.CharField(default="Unkown", max_length=50),
        ),
    ]
