# Generated by Django 4.2.5 on 2023-10-01 05:33

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_roommessage_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="roommessage",
            name="image",
        ),
        migrations.AddField(
            model_name="roommessage",
            name="attachment",
            field=models.FileField(
                blank=True, null=True, upload_to=chat.models.get_room_image_upload_path
            ),
        ),
    ]
