# Generated by Django 4.2.5 on 2023-10-24 07:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_rename_about_groups_groups_about_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="friend_request",
            name="groups_name",
            field=models.CharField(default="NO", max_length=50),
        ),
    ]
