# Generated by Django 4.2.5 on 2023-10-07 15:52

import chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_friendroom_fmmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fmmessage',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to=chat.models.get_friend_files_path),
        ),
    ]
