# Generated by Django 4.2.5 on 2023-10-10 03:35

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0006_alter_fmmessage_attachment'),
    ]

    operations = [
        migrations.CreateModel(
            name='LINK',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(help_text='Enter a link of a website', max_length=100, unique=True)),
                ('name', models.CharField(help_text='Enter the name of a website', max_length=100)),
                ('image', models.ImageField(blank=True, null=True, upload_to='link_image')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
