# Generated by Django 3.2.21 on 2023-10-24 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_alter_friend_request_groups_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='show_name',
            field=models.CharField(default='Post_Showname', max_length=128),
        ),
        migrations.AddField(
            model_name='room',
            name='show_name',
            field=models.CharField(default='Showname', max_length=100),
        ),
    ]
