# Generated by Django 3.2.21 on 2023-10-24 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20231024_1904'),
    ]

    operations = [
        migrations.AddField(
            model_name='groups',
            name='show_name',
            field=models.CharField(default='Group_Showname', max_length=128),
        ),
    ]
