# Generated by Django 4.2.5 on 2023-10-12 17:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_link"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="link",
            name="image",
        ),
    ]
