# Generated by Django 3.2.21 on 2023-10-24 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_remove_link_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='show_name',
            field=models.CharField(default='Showname', max_length=100),
        ),
    ]
